---
services:

  pipeline:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    command:
      - speech-to-speech
      - --mode
      - socket
      - --recv_host
      - 0.0.0.0
      - --send_host
      - 0.0.0.0
      - --llm_backend
      - transformers
      - --model_name
      - microsoft/Phi-3-mini-4k-instruct
      - --init_chat_role
      - system
      - --init_chat_prompt
      - "You are a helpful assistant"
    expose:
      - 12345/tcp
      - 12346/tcp
    ports:
      - 12345:12345/tcp
      - 12346:12346/tcp
    volumes:
      - ./cache/:/root/.cache/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
