from dataclasses import dataclass, field
from typing import Optional


@dataclass
class VisionModelHandlerArguments:
    vision_backend: str = field(
        default="none",
        metadata={
            "help": "Optional backend for image-only routing. Use 'none', 'responses-api', 'transformers', or 'mlx-lm'."
        },
    )
    vision_model_name: Optional[str] = field(
        default=None,
        metadata={
            "help": "Model used by the optional vision router. Required when --vision_backend is not 'none'."
        },
    )
    vision_device: str = field(
        default="cuda",
        metadata={"help": "Device for local vision routing backends. Default is 'cuda'."},
    )
    vision_torch_dtype: str = field(
        default="float16",
        metadata={"help": "Torch dtype for local vision routing backends. Default is 'float16'."},
    )
    vision_gen_max_new_tokens: int = field(
        default=256,
        metadata={"help": "Maximum tokens generated by the vision router. Default is 256."},
    )
    vision_gen_temperature: float = field(
        default=0.0,
        metadata={"help": "Sampling temperature for local vision routing. Default is 0.0."},
    )
    vision_gen_do_sample: bool = field(
        default=False,
        metadata={"help": "Whether local vision routing should sample. Default is False."},
    )
    vision_responses_api_base_url: Optional[str] = field(
        default=None,
        metadata={"help": "Base URL for a Responses API-compatible vision backend. Default is None."},
    )
    vision_responses_api_api_key: Optional[str] = field(
        default=None,
        metadata={"help": "API key for a Responses API-compatible vision backend. Default is None."},
    )
    vision_responses_api_request_timeout_s: float = field(
        default=20.0,
        metadata={"help": "Read timeout for Responses API vision routing requests. Default is 20 seconds."},
    )
    vision_responses_api_disable_thinking: bool = field(
        default=True,
        metadata={
            "help": "Disable provider-side thinking/reasoning for non-OpenAI Responses API vision backends when supported."
        },
    )
